apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"echo"},"name":"echo","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"echo"}},"template":{"metadata":{"labels":{"app":"echo"}},"spec":{"containers":[{"image":"kicbase/echo-server:1.0","name":"echo","ports":[{"containerPort":8080}]}]}}}}
    creationTimestamp: "2025-12-15T11:08:56Z"
    generation: 4
    labels:
      app: echo
      environement: staging
    name: echo
    namespace: default
    resourceVersion: "46625"
    uid: c85657f5-4aa7-4155-a576-3828f9364d9a
  spec:
    progressDeadlineSeconds: 600
    replicas: 10
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: echo
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: echo
      spec:
        containers:
        - image: kicbase/echo-server:1.0
          imagePullPolicy: IfNotPresent
          name: echo
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 10
    conditions:
    - lastTransitionTime: "2025-12-15T11:08:56Z"
      lastUpdateTime: "2025-12-15T11:08:58Z"
      message: ReplicaSet "echo-79548f6d55" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-12-15T11:10:48Z"
      lastUpdateTime: "2025-12-15T11:10:48Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 4
    readyReplicas: 10
    replicas: 10
    updatedReplicas: 10
kind: List
metadata:
  resourceVersion: ""
