services:
  db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: super
    volumes:
      - ./sql-init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:5432

  api:
    image: movieapi:${TAG_API}
    environment:
      DB_URL: postgresql+psycopg2://postgres:super@db/postgres
    ports:
      - ${API_PORT}:8080
